/**
 * @author Cludio Menghi
 *  
 */
package se.got;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.IOException;

import javax.imageio.ImageIO;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;

import se.got.panels.PatternSelectionPanel;
import se.got.panels.RobotSelectionPanel;

public class Co4robotsGUI extends javax.swing.JFrame {

	public static final Color REDCO4ROBOTS = new Color(157, 15, 0);
	public static final Color GRAYCO4ROBOTS = new Color(105, 105, 105);
	public static final Font FONT = new Font("Arial", Font.PLAIN, 16);
	public static final Font FONTTITLE = new Font("Arial", Font.BOLD, 16);

	private Model model;

	public static JTabbedPane tabbedPane;
	private javax.swing.JPanel patternJPanel;
	private javax.swing.JPanel jPanelLogo;

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private final static String TITLE = "PsAlMISt: Pattern bAsed MIssion Specifier";

	private static Subscriber sub;

	public final static Color BACKGROUNDCOLOR = Color.WHITE;

	public Co4robotsGUI() {
		super();
		
		this.model = Model.getModel();
		UIManager.put("ComboBox.background", new ColorUIResource(Color.WHITE));

		initComponents();
		System.out.println("GUI loaded");

	}

	public void showEditor() {
		setLocationRelativeTo(null); // center?
		setVisible(true);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {
		setLayout(new BorderLayout());

		tabbedPane = new JTabbedPane();

		tabbedPane.add("Robot management", new RobotSelectionPanel(model));
		patternJPanel = new javax.swing.JPanel();
		jPanelLogo = new javax.swing.JPanel();

		getContentPane().setBackground(BACKGROUNDCOLOR);
		patternJPanel.setBackground(BACKGROUNDCOLOR);
		jPanelLogo.setBackground(BACKGROUNDCOLOR);
		jPanelLogo.setBackground(Color.WHITE);

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle(TITLE);
		
		try {
			BufferedImage myPicture3;
			myPicture3 = ImageIO.read(this.getClass().getClassLoader().getResourceAsStream("images/co4robotsLogo20px.png"));
			// PsAlMIStLogo.png
			ImageIcon icon3 = new ImageIcon(myPicture3);

		
			
			setIconImage(icon3.getImage());
			setVisible(true);
			
		} catch (IOException e) {
			e.printStackTrace();
		}
		
		
		setResizable(true);

		jPanelLogo.setLayout(new BorderLayout());

		BufferedImage myPicture;
		try {
			myPicture = ImageIO.read(getClass().getClassLoader().getResourceAsStream("images/PsAlMIStLogo.png"));

			// PsAlMIStLogo.png
			ImageIcon icon = new ImageIcon(myPicture);
			icon = new ImageIcon(icon.getImage().getScaledInstance(icon.getIconWidth() / 3, icon.getIconHeight() / 3,
					java.awt.Image.SCALE_SMOOTH));
			JLabel picLabel = new JLabel(icon);
			jPanelLogo.add(picLabel, BorderLayout.CENTER);


		} catch (IOException e) {
			e.printStackTrace();
		}

		JPanel mainPanel = new JPanel();
		mainPanel.setBackground(Co4robotsGUI.BACKGROUNDCOLOR);
		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(mainPanel);
		mainPanel.setLayout(layout);

		layout.setAutoCreateGaps(true);
		layout.setAutoCreateContainerGaps(true);

		layout.createSequentialGroup();

		layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(jPanelLogo)
				.addComponent(tabbedPane));

		layout.setVerticalGroup(layout.createSequentialGroup().addComponent(jPanelLogo).addComponent(tabbedPane));

		setBounds(0, 0, (int) Toolkit.getDefaultToolkit().getScreenSize().getWidth(),
				(int) Toolkit.getDefaultToolkit().getScreenSize().getHeight());

		this.getContentPane().setBackground(BACKGROUNDCOLOR);
		this.getContentPane().setPreferredSize(Toolkit.getDefaultToolkit().getScreenSize());

		this.getContentPane().add(mainPanel);
		setVisible(false);

		this.setBackground(BACKGROUNDCOLOR);
		this.getContentPane().setBackground(BACKGROUNDCOLOR);
		this.setResizable(true);
	}
	

	public static void main(String args[]) {
		/* Create and display the form */

		Co4robotsGUI c4gui=new Co4robotsGUI();
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				(c4gui).showEditor();
			}
		});
		

	}

}
